#CXX = /usr/local/Cellar/gcc/8.2.0/bin/g++-8
CXX = clang++

unique2: unique2.cpp
	$(CXX) -std=c++17 -Wall -g -o unique2 unique2.cpp
	#$(CXX) -Wall -g -o unique1 unique1.cpp

unique1: unique1.cpp
	$(CXX) -std=c++17 -Wall -g -o unique1 unique1.cpp
	#$(CXX) -Wall -g -o unique1 unique1.cpp